#{{- if .Values.objects.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mytest
  template:
    metadata:
      labels:
        app: mytest
    spec:
      containers:
      - image: robertsilvatech/flask-color
        name: flask-color
        envFrom: 
        {{- if (hasKey .Values "configGlobal") }}
        {{- if and (hasKey .Values.configGlobal "enabled") .Values.configGlobal.enabled }}
        - configMapRef:
          name: my-config-global
        {{- end }}         
        {{- end }}
#{{- end }}